#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORMTHEME="qt5ct"

# export GTK_IM_MODULE=fcitx5
# export QT_IM_MODULE=fcitx5
# export XMODIFIERS="@im=fcitx5"
# cn
export LANG="zh-CN.UTF-8" 
export LC_ALL="en_US.UTF-8"
#  fcitx
# export GTK_IM_MODULE="fcitx"
# export QT_IM_MODULE="fcitx"
# export XMODIFIERS="@im=fcitx"
# export INPUT_METHOD="fcitx"
# export XIM="fcitx"
# export XIM_PROGRAM="fcitx"
# export SDL_IM_MODULE="fcitx"
# export GLFW_IM_MODULE="ibus"

# XIM=fcitx5
# XIM_PROGRAM=fcitx5
# GTK_IM_MODULE=fcitx5
# QT_IM_MODULE=fcitx5
# XMODIFIERS=@im=fcitx5
# SDL_IM_MODULE=fcitx5
# GLFW_IM_MODULE=fcitx5

GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=ibus

pgrep -x fcitx5 > /dev/null || fcitx5 &!
# pgrep -x crow > /dev/null || crow &
# picom  -b &
fastcompmgr &
pgrep -x FlClash> /dev/null || flclash &
pgrep -x blueman-applet > /dev/null || blueman-applet &
pgrep -x wechat > /dev/null || wechat.sh &

# synergy &
#pgrep -x synergy> /dev/null || synergy &
dunst &!
# pgrep -x input-leap > /dev/null || input-leap &!

pgrep -x rustdesk > /dev/null || rustdesk -service &!
/usr/bin/copyq &!

feh --bg-scale $HOME/Pictures/bg2.png

polybar example &

# /usr/lib/polkit-kde-authentication-agent-1 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &!

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         1
#bspc config window_gap          2
bspc config bottom_padding 0
# bspc config top_padding 30

bspc config normal_border_color \#617071
bspc config focused_border_color \#5DADE2

#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

bspc config border_width       1
# 设置窗口之间的空隙
bspc config window_gap       3

bspc config normal_border_color \#617071
bspc config focused_border_color \#555DADE2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config split_ratio            0.5
bspc config top_padding          0


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a jetbrains-phpstorm desktop='^1'
bspc rule -a google-chrome desktop='^2'
bspc rule -a apifox desktop='^3'
bspc rule -a jetbrains-datagrip desktop='^4'
bspc rule -a jetbrains-studio desktop='^5'
bspc rule -a 小黑屋 desktop='^5'
bspc rule -a "\345\215\263\346\227\266\350\256\276\350\256\241" desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a copyq state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "Crow Translate" state=floating
bspc rule -a Crow state=floating
bspc rule -a crow-translate state=floating
bspc rule -a crow state=floating
bspc rule -a todesk state=floating
bspc rule -a ToDesk state=floating
# bspc rule -a wechat state=floating
bspc rule -a wechat sticky=off state=floating
bspc rule -a qq sticky=off state=floating
bspc rule -a QQ sticky=off state=floating


bspc rule -a zenity state=floating
bspc rule -a scrcpy state=floating
bspc rule -a Indicator-stickynotes state=floating

# init windows
#source ~/app/bspwmstatus.sh
#init_bspwm_node_flags

# xset s 300 5
# xss-lock -n /usr/libexec/xsecurelock/dimmer -l -- betterlockscreen --lock


# pgrep -x alacritty> /dev/null || alacritty &

# autostart
bspc rule -a jetbrains-phpstorm desktop=I && /home/yyl/.local/share/JetBrains/Toolbox/apps/phpstorm/bin/phpstorm &

bspc rule -a Google-chrome desktop=II && google-chrome-stable &

bspc rule -a jetbrains-datagrip desktop=IV && /home/yyl/.local/share/JetBrains/Toolbox/apps/datagrip/bin/datagrip &

