general {
   hide_cursor=true
   disable_screensaver = true
   disable_power_management = true
}

background {
    # color = rgba(0, 1, 0, 0.1)  # Black background
  # 设置路径为当前壁纸的路径
    # path = 这一行需要被注释掉或删除，因为我们将使用 screenshot 功能
    # path = /path/to/static/image.jpg

    # 启用屏幕截图功能，这样锁屏背景就是当前的桌面状态（包括当前壁纸）
    path = screenshot

    # 可选：对截图背景进行模糊处理，可以营造毛玻璃效果
    blur_size = 1
    blur_passes = 4
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
}

input-field {
    size = 200, 50
    position = 0, -20
    halign = center
    valign = center
    outline_thickness = 2
    placeholder_text = Password...
}

